import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import { ThemeProvider } from '@/components/ThemeProvider';
import ToastProvider from '@/components/ToastProvider';
import ErrorBoundary from '@/components/ErrorBoundary';

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'IProtocol CENCO V1',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-gray-900 transition-colors">
        <ThemeProvider>
          <ErrorBoundary>
            <main className="min-h-screen bg-white dark:bg-gray-900 flex flex-col items-center">
              {children}
              <Analytics />
            </main>
            <ToastProvider />
          </ErrorBoundary>
        </ThemeProvider>
      </body>
    </html>
  )
}
