import './globals.css'
import { Analytics } from '@vercel/analytics/react';

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'IProtocol CENCO V1',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
          <Analytics />
        </main>
      </body>
    </html>
  )
}
